import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './app.css'
import { logo, header, headerContent } from './layout.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pretendard = localFont({
  src: [
    {
      path: '../public/fonts/Pretendard-Bold.subset.woff2',
      weight: '700',
    },
    {
      path: '../public/fonts/Pretendard-SemiBold.subset.woff2',
      weight: '600',
    },
    {
      path: '../public/fonts/Pretendard-Medium.subset.woff2',
      weight: '500',
    },
    {
      path: '../public/fonts/Pretendard-Regular.subset.woff2',
      weight: '400',
    },
    {
      path: '../public/fonts/Pretendard-Light.subset.woff2',
      weight: '300',
    },
  ],
  variable: '--font-pretendard',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <header className={header}>
          <div className={headerContent}>
            <span className={logo}>GLANCE</span>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
